# Generated by Django 5.2 on 2025-05-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=210)),
                ('email', models.CharField(max_length=210)),
                ('telefono', models.CharField(max_length=25)),
                ('categoriaConsulta', models.CharField(choices=[('1', 'Coleccion'), ('2', 'Sugerencia'), ('3', 'Queja'), ('4', 'Otro')], max_length=1)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
