# Generated by Django 5.2 on 2025-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('pantalon', 'Pantalon'), ('remera', 'Remera'), ('top', 'Top'), ('vestido', 'Vestido'), ('buzo', 'Buzo'), ('campera', 'Campera'), ('accesorio', 'Accesorio')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prendas/')),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.AlterField(
            model_name='consultas',
            name='email',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
