# Generated by Django 5.2 on 2025-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_productos_alter_consultas_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('1', 'Pantalon'), ('2', 'Remera'), ('3', 'Top'), ('4', 'Vestido'), ('5', 'Buzo'), ('6', 'Campera'), ('7', 'Accesorio')], max_length=20),
        ),
    ]
