# Generated by Django 5.2 on 2025-06-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_productos_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas',
            name='categoriaConsulta',
        ),
        migrations.AddField(
            model_name='consultas',
            name='categoria_detectada',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
