# Generated by Django 5.2 on 2025-06-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_usuariospermitidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariospermitidos',
            name='codigo_validacion',
            field=models.CharField(max_length=6),
        ),
    ]
