# Generated by Django 5.2 on 2025-07-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_usuariospermitidos_codigo_validacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('1', 'Pantalon'), ('2', 'Remera'), ('3', 'Top'), ('4', 'Vestido'), ('5', 'Buzo'), ('6', 'Campera'), ('7', 'Accesorio')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='consultas',
            table='consultas',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='usuariospermitidos',
            table='usuarios_permitidos',
        ),
    ]
