# Generated by Django 5.2 on 2025-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_consultas_email_alter_productos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
