# Generated by Django 5.2 on 2025-09-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_codigovalidacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuariosPermitidos',
        ),
    ]
